### ISSUE TITLE
Alastria connectivity questions

### ISSUE THREAD

**Issue by michaelkunzmann-sap** [alastria/alastria-node#140]
Hi,

We are interested in joining the Alastria network and are currently playing a little bit with the Alastria setup and have some general technical questions.

When we run the start script (for a general node), in the beginning, we are connecting to several Constellation nodes, but no Geth nodes. So we assume, we have to get "on the list" of the permissioned nodes. 

We found the following file of permissioned nodes here: https://github.com/alastria/alastria-node/blob/feature/ibft/data/permissioned-nodes_general.json

Furthermore, the documentation states that we would also need to issue a pull request and our contact information here: https://github.com/alastria/alastria-node/blob/feature/ibft/DIRECTORY_REGULAR.md

Our questions: 
- Is that everything that needs to be done to join the network and issue transactions? 
- How is the updated ```permissioned-nodes_general.json``` distributed to the other network participants and who decides on this? How fast does that happen? 
- If we would become a new participant, what needs to be done from our side in the process of more institutions to join?

**Comment by esanchma** [comment]
I thought that this issue was done, but there are some questions that merit an answer:

> Is that everything that needs to be done to join the network and issue transactions?

The init script modifies the permissioning templates (those json files) in such a way that you can send a pull request with the same tree. You only need to add your contact details to the markdown files. When the pull request is merged, validator nodes will pull those changes and accept peering with your node.

> How is the updated permissioned-nodes_general.json distributed to the other network participants and who decides on this? How fast does that happen?

validator nodes are supposed to do a pull when a PR is accepted and run `restart.sh onlyUpdate` to merge the new nodes to their permissioning list. The operation is performed with the node running (with no downtime). There is a small team with repository access that accepts those pull request if they are complete (they have contact details) and don't break anything obvious.

> If we would become a new participant, what needs to be done from our side in the process of more institutions to join?

regular non mining nodes don't need to do anything. validator node operators need to subscribe to the repository and add new nodes when they are accepted. Usually those operations are discussed in [Slack](https://alastria.slack.com/), where anyone with interest in Alastria is welcomed.
