### ISSUE TITLE
init.sh script does not use newest libsodium

### ISSUE THREAD

**Issue by tsteinmetz-sap** [alastria/alastria-node#346]
Network: Arrakis
Node type: Regular 
Node name: REG_SAP_2_4_00
Geth version: 1.7.2-beta
OS & Version: Ubuntu 18.04.1 LTS

#### Expected behavior
* init.sh should use the latest installed libraries on the system (e.g. libsodium.so)
* init.sh should stop with an error message, that the initialization failed

#### Behavior obtained
* init.sh is stopping with an error that an specific (and old) version of a library was not found: "libsodium.so.18 not found (23 installed)".
* init.sh is not prominently stating that the whole initialization did not succeed. In fact, starting geth was possible without problems. Starting constellation stated an infinite "waiting for 5 sec" loop.

#### Steps to reproduce the error
This happened after we've updated&upgraded ubuntu to the latest release and removed unnecessary packages.

#### Workaround
Create a symlink that links the specific version to the latest one (or install older package again):
```
cd /usr/lib/x86_64-linux-gnu/
sudo ln -s libsodium.so libsodium.so.18
```

**Comment by netmanito** [comment]
Hi @tsteinmetz-sap,
Thanks for the information. This issue appears as you said on Ubuntu 18. The reason is that the `alastria-node` was developed and works on top of Ubuntu 16 and, there seems to be differences between these versions.
We might try to include a fix for this in feature releases.
You're also welcome to help on it if you want.
Thanks!
