### ISSUE TITLE
How to use Metamask with Alastria?

### ISSUE THREAD

**Issue by dgrmunch** [alastria/alastria-node#366]
Simple questions :)

a) Can we connect to a public node by Metamask to use web3.js in our dApps and write and read from the Alastria blockchain?

In order to implement dApps that can work with smart contracts deployed in Alastria we need to be able to connect our browser to the network. 
For everyone who wants to use a dApp published on the platform, running its own Alastria node locally does not make sense at all. On one hand, an Alastria node requires an specific OS (Ubuntu 16) and specific hardware characteristics. On the other, it would not scale considering that every node in a Proof of Authority network should be authorized by the network to be part of it.
If your dApp has 1000 users you can not ask all of them to install a node.

So I imagine that there is another way to do it. Something like Infura, maybe? Another trick? Or only authorized users can "write" on the blockchain? What about reading from smart contracts public functions?

b) If gas price is 0 in Alastria, how do users pay to execute their transactions? How do we avoid spam and an abuse of the system?

**Comment by iasinDev** [comment]
Hi, 

in my opinion,

a) you can redirect the traffic of your public app at your backup through a connection to your_node/or_other_network_node, this way it would work...

Although that I had troubles connecting metamask due to EIP-155 compliance, to solve them I did a PR: https://github.com/alastria/alastria-node/pull/362

b) in quorum although gas price 0, you have a limit per transaction established, so I think adjusting this parameter is the key.

**Comment by NachoDeLaVega** [comment]
Hi. Alastria is a Permissioned Blockchain. This means that the DApps that run on it must have the approval of the partners. In this case the partner allows access to its node through the web3j interface.

As iasinDev says, actual version of Alastria is not EIP-155 compliance, but the next version yes it will be. It will be available soon

**Comment by JuanLuisGozaloFdez** [comment]
New Alastria Telsius Network solves the EIP-155 compliance. If you want to move your node please Contact Core Support Team indicating Arrakis Node name. If you wish yo add a new Node to Telsius Network you must ask for It following testnet2 instructions.

**Comment by dgrmunch** [comment]
Thanks @JuanLuisGozaloFdez! I published this post a month ago, before moving to Telsius. 
Is there any recipe about how to make Metamask work with Alastria once you are in Telsius? 
I mean, should we just execute the "geth attach..." command and add a remote connection to Metamask. Or there are more steps required?
Thanks!

**Comment by NachoDeLaVega** [comment]
In Metamask you need to create a new entry in "custom RPC" and add in "new RPC Url" a url of Telsius node network with the format "http: //ip_node_telsius: 22000"

**Comment by rogargon** [comment]
Very interested in this issue. What is the recommended approach to interacting from Web apps with a Telsius node (for instance through Metamask)? 

My understanding is that adding the node as a new Metamask "Custom RPC" connection is risky because it would require the node to be open to connections from the Web. 

Maybe something like `--rpccorsdomain` might help here? Or is it better to push all interactions with the node through a backend for the Web app?

**Comment by andresag** [comment]
There are a few things to consider on this topic that are new to Telsius.

When you setup a node in Telsius, using the provided docker images, it comes with [Access Point](https://github.com/alastria/alastria-access-point) pre-installed and working in whitelist mode by default. While whitelisting is the preferred mode in terms of node security, it is not possible to use browser wallets (such as Metamask) under this method, since you cannot know every IP address that will be invoking the application beforehand (e.g. coming from a cell phone).

In order to avoid this, it is possible to setup Access Point in blacklist mode. That way, the node will still filter calls to critical RPC families and protected against DoS attacks, but it won't deny requests based on IP, unless explicitly told so.

Regarding ```--rpccorsdomain``` there's already a [pull request](https://github.com/alastria/alastria-node/pull/473) to include this flag, that we are currently testing.
